version: "3.9"
services:
  frontend:
    build: ./frontend
    image: "frontend"
    container_name: frontend
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
  backend:
    build: ./backend
    image: "backend"
    container_name: backend
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  postgres:
    image: postgres:13-alpine
    container_name: postgres
    env_file:
      - ./.env
    environment:
      POSTGRES_PGDATA: /var/lib/postgresql/data
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: unless-stopped
